apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: guest-book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: guest-book-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guest-book-app

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
