apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: guestbook-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: guestbook-service
    app: guestbook-app
