apiVersion: v1
kind: Service
metadata:
  name: guest-book-service
  labels:
    name: guest-book-service
    app: guest-book-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: guest-book-service
    app: guest-book-app
